Layout/LineLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
